// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocumentService: open, analyze and preview PDFs (04 §1.1 DocumentService).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../internal/engine/models.js";

/**
 * AnalyzeDocument starts layout analysis for a PDF and returns a new job id.
 * Progress arrives via `job:progress`; completion via `job:state` (ANALYZED).
 * @param {string} path
 * @param {string} password
 * @param {string} pagesSpec
 * @returns {$CancellablePromise<string>}
 */
export function AnalyzeDocument(path, password, pagesSpec) {
    return $Call.ByID(70010973, path, password, pagesSpec);
}

/**
 * GetPagePreview rasterizes a page of the given PDF to a base64 PNG data URL.
 * @param {string} pdfPath
 * @param {number} page
 * @param {number} zoom
 * @returns {$CancellablePromise<string>}
 */
export function GetPagePreview(pdfPath, page, zoom) {
    return $Call.ByID(4180426617, pdfPath, page, zoom);
}

/**
 * OpenDocument returns lightweight metadata (page count, text-layer, encryption).
 * @param {string} path
 * @param {string} password
 * @returns {$CancellablePromise<engine$0.DocMeta | null>}
 */
export function OpenDocument(path, password) {
    return $Call.ByID(4202096249, path, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PickPDF shows a native open dialog and returns the chosen PDF path ("" if cancelled).
 * @returns {$CancellablePromise<string>}
 */
export function PickPDF() {
    return $Call.ByID(1824963833);
}

/**
 * PickSavePath shows a native save dialog for the output file. The filter is
 * chosen from the default filename's extension (.pdf / .docx / .hwpx).
 * @param {string} defaultName
 * @returns {$CancellablePromise<string>}
 */
export function PickSavePath(defaultName) {
    return $Call.ByID(3552167747, defaultName);
}

// Private type creation functions
const $$createType0 = engine$0.DocMeta.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
