// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocumentService: open, analyze and preview PDFs (04 §1.1 DocumentService).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../internal/engine/models.js";

/**
 * AnalyzeDocument starts layout analysis for a PDF and returns a new job id.
 * Progress arrives via `job:progress`; completion via `job:state` (ANALYZED).
 */
export function AnalyzeDocument(path: string, password: string, pagesSpec: string): $CancellablePromise<string> {
    return $Call.ByID(70010973, path, password, pagesSpec);
}

/**
 * GetPagePreview rasterizes a page of the given PDF to a base64 PNG data URL.
 */
export function GetPagePreview(pdfPath: string, page: number, zoom: number): $CancellablePromise<string> {
    return $Call.ByID(4180426617, pdfPath, page, zoom);
}

/**
 * OpenDocument returns lightweight metadata (page count, text-layer, encryption).
 */
export function OpenDocument(path: string, password: string): $CancellablePromise<engine$0.DocMeta | null> {
    return $Call.ByID(4202096249, path, password);
}

/**
 * PickPDF shows a native open dialog and returns the chosen PDF path ("" if cancelled).
 */
export function PickPDF(): $CancellablePromise<string> {
    return $Call.ByID(1824963833);
}

/**
 * PickSavePath shows a native save dialog for the output file. The filter is
 * chosen from the default filename's extension (.pdf / .docx / .hwpx).
 */
export function PickSavePath(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(3552167747, defaultName);
}
