// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GlossaryService exposes glossary CRUD + CSV I/O to the frontend
 * (04-api-spec.md §1.1 GlossaryService).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateGlossary(name: string): $CancellablePromise<$models.Glossary | null> {
    return $Call.ByID(1698029389, name);
}

export function DeleteGlossary(id: number): $CancellablePromise<void> {
    return $Call.ByID(2396433414, id);
}

export function DeleteTerm(glossaryID: number, termID: number): $CancellablePromise<void> {
    return $Call.ByID(2419227216, glossaryID, termID);
}

/**
 * ExportCSV opens a save dialog and exports the glossary to CSV.
 */
export function ExportCSV(glossaryID: number, suggestedName: string): $CancellablePromise<void> {
    return $Call.ByID(1731998605, glossaryID, suggestedName);
}

/**
 * ImportCSV opens a file dialog and imports the chosen CSV into the glossary.
 */
export function ImportCSV(glossaryID: number): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByID(2571781756, glossaryID);
}

export function ListGlossaries(): $CancellablePromise<$models.GlossaryMeta[] | null> {
    return $Call.ByID(1148380005);
}

export function ListTerms(glossaryID: number, query: string, offset: number, limit: number): $CancellablePromise<$models.TermsPage> {
    return $Call.ByID(3175741144, glossaryID, query, offset, limit);
}

export function RenameGlossary(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3815661015, id, name);
}

export function UpsertTerm(glossaryID: number, term: $models.Term): $CancellablePromise<$models.Term | null> {
    return $Call.ByID(3511732504, glossaryID, term);
}
