// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GlossaryService exposes glossary CRUD + CSV I/O to the frontend
 * (04-api-spec.md §1.1 GlossaryService).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.Glossary | null>}
 */
export function CreateGlossary(name) {
    return $Call.ByID(1698029389, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGlossary(id) {
    return $Call.ByID(2396433414, id);
}

/**
 * @param {number} glossaryID
 * @param {number} termID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTerm(glossaryID, termID) {
    return $Call.ByID(2419227216, glossaryID, termID);
}

/**
 * ExportCSV opens a save dialog and exports the glossary to CSV.
 * @param {number} glossaryID
 * @param {string} suggestedName
 * @returns {$CancellablePromise<void>}
 */
export function ExportCSV(glossaryID, suggestedName) {
    return $Call.ByID(1731998605, glossaryID, suggestedName);
}

/**
 * ImportCSV opens a file dialog and imports the chosen CSV into the glossary.
 * @param {number} glossaryID
 * @returns {$CancellablePromise<$models.ImportResult | null>}
 */
export function ImportCSV(glossaryID) {
    return $Call.ByID(2571781756, glossaryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GlossaryMeta[]>}
 */
export function ListGlossaries() {
    return $Call.ByID(1148380005).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} glossaryID
 * @param {string} query
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<$models.TermsPage>}
 */
export function ListTerms(glossaryID, query, offset, limit) {
    return $Call.ByID(3175741144, glossaryID, query, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {number} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameGlossary(id, name) {
    return $Call.ByID(3815661015, id, name);
}

/**
 * @param {number} glossaryID
 * @param {$models.Term} term
 * @returns {$CancellablePromise<$models.Term | null>}
 */
export function UpsertTerm(glossaryID, term) {
    return $Call.ByID(3511732504, glossaryID, term).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Glossary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ImportResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GlossaryMeta.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.TermsPage.createFrom;
const $$createType7 = $models.Term.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
