// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JobService: translate, render, cancel and query jobs (04 §1.1 JobService).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelJob signals the engine to cancel; completed work is preserved.
 */
export function CancelJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3598642699, jobID);
}

/**
 * DiscardJob deletes a job's temporary translation and rendered output so the user
 * can start the document over from scratch. The analyzed IR is kept (no re-analyze);
 * progress counters and state are reset. The job then drops out of the resume list.
 */
export function DiscardJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(93628335, jobID);
}

/**
 * ExportOutput writes the translated document to a user-chosen destination as a
 * flowing .docx or .hwpx file (generated on demand from the IR + translation).
 */
export function ExportOutput(jobID: string, dst: string, format: string): $CancellablePromise<void> {
    return $Call.ByID(2244236885, jobID, dst, format);
}

/**
 * GetJob returns the current job record (state, paths).
 */
export function GetJob(jobID: string): $CancellablePromise<$models.Job | null> {
    return $Call.ByID(480001849, jobID);
}

/**
 * ListResumable returns jobs that can be continued (newest first) for the startup
 * resume list. Returned copies are safe to marshal to the frontend.
 */
export function ListResumable(): $CancellablePromise<($models.Job | null)[] | null> {
    return $Call.ByID(821607474);
}

/**
 * ResumeJob continues an interrupted/cancelled/failed translation from its saved
 * checkpoint (only the remaining TUs are translated), then renders. Options come
 * from the persisted job so it works across an app restart.
 */
export function ResumeJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(128243500, jobID);
}

/**
 * RetranslateUnit re-runs one failed/edited TU, then re-renders the PDF (UC-03).
 */
export function RetranslateUnit(jobID: string, tuID: string): $CancellablePromise<void> {
    return $Call.ByID(1032173893, jobID, tuID);
}

/**
 * SaveOutput copies a finished job's output.pdf to a user-chosen destination.
 */
export function SaveOutput(jobID: string, dst: string): $CancellablePromise<void> {
    return $Call.ByID(4119100330, jobID, dst);
}

/**
 * StartTranslation runs translate → render for an analyzed job, emitting events.
 * Returns immediately; watch `job:state` for RENDERING/DONE and the output path.
 */
export function StartTranslation(jobID: string, opts: $models.TranslateJobOptions): $CancellablePromise<void> {
    return $Call.ByID(836648781, jobID, opts);
}
