// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JobService: translate, render, cancel and query jobs (04 §1.1 JobService).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelJob signals the engine to cancel; completed work is preserved.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function CancelJob(jobID) {
    return $Call.ByID(3598642699, jobID);
}

/**
 * DiscardJob deletes a job's temporary translation and rendered output so the user
 * can start the document over from scratch. The analyzed IR is kept (no re-analyze);
 * progress counters and state are reset. The job then drops out of the resume list.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function DiscardJob(jobID) {
    return $Call.ByID(93628335, jobID);
}

/**
 * ExportOutput writes the translated document to a user-chosen destination as a
 * flowing .docx or .hwpx file (generated on demand from the IR + translation).
 * @param {string} jobID
 * @param {string} dst
 * @param {string} format
 * @returns {$CancellablePromise<void>}
 */
export function ExportOutput(jobID, dst, format) {
    return $Call.ByID(2244236885, jobID, dst, format);
}

/**
 * GetJob returns the current job record (state, paths).
 * @param {string} jobID
 * @returns {$CancellablePromise<$models.Job | null>}
 */
export function GetJob(jobID) {
    return $Call.ByID(480001849, jobID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListResumable returns jobs that can be continued (newest first) for the startup
 * resume list. Returned copies are safe to marshal to the frontend.
 * @returns {$CancellablePromise<($models.Job | null)[]>}
 */
export function ListResumable() {
    return $Call.ByID(821607474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ResumeJob continues an interrupted/cancelled/failed translation from its saved
 * checkpoint (only the remaining TUs are translated), then renders. Options come
 * from the persisted job so it works across an app restart.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function ResumeJob(jobID) {
    return $Call.ByID(128243500, jobID);
}

/**
 * RetranslateUnit re-runs one failed/edited TU, then re-renders the PDF (UC-03).
 * @param {string} jobID
 * @param {string} tuID
 * @returns {$CancellablePromise<void>}
 */
export function RetranslateUnit(jobID, tuID) {
    return $Call.ByID(1032173893, jobID, tuID);
}

/**
 * SaveOutput copies a finished job's output.pdf to a user-chosen destination.
 * @param {string} jobID
 * @param {string} dst
 * @returns {$CancellablePromise<void>}
 */
export function SaveOutput(jobID, dst) {
    return $Call.ByID(4119100330, jobID, dst);
}

/**
 * StartTranslation runs translate → render for an analyzed job, emitting events.
 * Returns immediately; watch `job:state` for RENDERING/DONE and the output path.
 * @param {string} jobID
 * @param {$models.TranslateJobOptions} opts
 * @returns {$CancellablePromise<void>}
 */
export function StartTranslation(jobID, opts) {
    return $Call.ByID(836648781, jobID, opts);
}

// Private type creation functions
const $$createType0 = $models.Job.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
