// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * About holds the program/author credits shown in the "정보" dialog.
 * Edit the constants below to change what is displayed. Empty fields are hidden.
 */
export interface About {
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "department": string;
    "organization": string;
    "year": string;
    "contact": string;
    "license": string;
}

/**
 * Glossary is a named set of terms.
 */
export interface Glossary {
    "id": number;
    "name": string;
    "created_at": string;
    "updated_at": string;
    "terms": (Term | null)[] | null;
}

/**
 * GlossaryMeta is a lightweight listing entry.
 */
export interface GlossaryMeta {
    "id": number;
    "name": string;
    "term_count": number;
    "updated_at": string;
}

/**
 * ImportResult reports CSV import counts (FR-62).
 */
export interface ImportResult {
    "added": number;
    "updated": number;
    "skipped": number;
}

/**
 * Job is the record of a translation job. It is persisted to <JobDir>/job.json so
 * an interrupted translation can be resumed after the app restarts.
 */
export interface Job {
    "id": string;
    "doc_id": string;
    "pdf_path": string;

    /**
     * PDF basename, for the resume list
     */
    "title": string;
    "job_dir": string;
    "ir_path": string;
    "translation_path": string;
    "out_path": string;
    "state": string;
    "error"?: string;

    /**
     * remembered for retranslate/resume
     */
    "style"?: string;

    /**
     * render mode, remembered for resume
     */
    "mode"?: string;

    /**
     * frozen glossary snapshot for retranslate/resume
     */
    "glossary_path"?: string;

    /**
     * translation progress (checkpointed count)
     */
    "done_tus"?: number;
    "total_tus"?: number;

    /**
     * pages fully translated (for the resume list)
     */
    "done_pages"?: number;

    /**
     * document page count
     */
    "total_pages"?: number;

    /**
     * 0-based fully-translated pages (to restore batches)
     */
    "done_page_list"?: number[] | null;
    "updated_at"?: string;
}

/**
 * LocalModelInfo is the snapshot the UI shows for the offline (local) engine.
 */
export interface LocalModelInfo {
    /**
     * remote | local
     */
    "mode": string;

    /**
     * llama-server binary bundled?
     */
    "bin_available": boolean;

    /**
     * GGUF downloaded/selected?
     */
    "model_present": boolean;
    "model_path": string;
    "model_name": string;
    "model_url": string;
    "size_mb": number;
    "running": boolean;
    "base_url": string;
}

/**
 * Settings is the persisted app configuration (subset of FR-72 for v1 slice).
 */
export interface Settings {
    "llm_base_url": string;
    "llm_model": string;
    "llm_api_key": string;
    "max_concurrency": number;

    /**
     * formal | concise
     */
    "style": string;

    /**
     * noto | nanum
     */
    "font_family": string;

    /**
     * replace | interleaved
     */
    "mode": string;

    /**
     * ko | en
     */
    "ui_language": string;

    /**
     * auto | en | ko | ja | zh … (document's language)
     */
    "source_lang": string;

    /**
     * Korean | English | …          (translation language)
     */
    "target_lang": string;

    /**
     * Local inference (offline) — run a bundled llama.cpp server against a local GGUF.
     * remote | local  (default remote)
     */
    "engine_mode": string;

    /**
     * download source for the GGUF
     */
    "local_model_url": string;

    /**
     * display name
     */
    "local_model_name": string;

    /**
     * remembered GGUF path (downloaded or picked)
     */
    "local_model_path": string;

    /**
     * integrity hash (computed on download; verified if set)
     */
    "local_model_sha256": string;

    /**
     * optional Hugging Face token for gated models
     */
    "hf_token": string;
}

/**
 * Term is a single glossary entry (03-detailed-design.md §3, §8.2).
 */
export interface Term {
    "id": number;
    "src": string;
    "dst": string;
    "domain": string;
    "priority": number;
    "case_sensitive": boolean;
    "match_inflections": boolean;
    "note": string;
}

/**
 * TermsPage is a paged term listing.
 */
export interface TermsPage {
    "terms": (Term | null)[] | null;
    "total": number;
}

/**
 * TranslateJobOptions mirrors 04 §1.1 TranslateJobOptions (subset for v1 slice).
 */
export interface TranslateJobOptions {
    /**
     * formal | concise
     */
    "style": string;
    "enforce_glossary": boolean;

    /**
     * replace | interleaved
     */
    "mode": string;

    /**
     * selected glossaries to apply
     */
    "glossary_ids": number[] | null;

    /**
     * 0-based pages for this batch (general-doc mode); empty = whole doc
     */
    "pages": number[] | null;
}
