// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * About holds the program/author credits shown in the "정보" dialog.
 * Edit the constants below to change what is displayed. Empty fields are hidden.
 */
export class About {
    /**
     * Creates a new About instance.
     * @param {Partial<About>} [$$source = {}] - The source object to create the About.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("department" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["department"] = "";
        }
        if (!("organization" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["organization"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["year"] = "";
        }
        if (!("contact" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contact"] = "";
        }
        if (!("license" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["license"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new About instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {About}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new About(/** @type {Partial<About>} */($$parsedSource));
    }
}

/**
 * Glossary is a named set of terms.
 */
export class Glossary {
    /**
     * Creates a new Glossary instance.
     * @param {Partial<Glossary>} [$$source = {}] - The source object to create the Glossary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("terms" in $$source)) {
            /**
             * @member
             * @type {(Term | null)[]}
             */
            this["terms"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Glossary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Glossary}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terms" in $$parsedSource) {
            $$parsedSource["terms"] = $$createField4_0($$parsedSource["terms"]);
        }
        return new Glossary(/** @type {Partial<Glossary>} */($$parsedSource));
    }
}

/**
 * GlossaryMeta is a lightweight listing entry.
 */
export class GlossaryMeta {
    /**
     * Creates a new GlossaryMeta instance.
     * @param {Partial<GlossaryMeta>} [$$source = {}] - The source object to create the GlossaryMeta.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("term_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["term_count"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlossaryMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlossaryMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlossaryMeta(/** @type {Partial<GlossaryMeta>} */($$parsedSource));
    }
}

/**
 * ImportResult reports CSV import counts (FR-62).
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["added"] = 0;
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * Job is the record of a translation job. It is persisted to <JobDir>/job.json so
 * an interrupted translation can be resumed after the app restarts.
 */
export class Job {
    /**
     * Creates a new Job instance.
     * @param {Partial<Job>} [$$source = {}] - The source object to create the Job.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("doc_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["doc_id"] = "";
        }
        if (!("pdf_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pdf_path"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * PDF basename, for the resume list
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("job_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["job_dir"] = "";
        }
        if (!("ir_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ir_path"] = "";
        }
        if (!("translation_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["translation_path"] = "";
        }
        if (!("out_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["out_path"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * remembered for retranslate/resume
             * @member
             * @type {string | undefined}
             */
            this["style"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * render mode, remembered for resume
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * frozen glossary snapshot for retranslate/resume
             * @member
             * @type {string | undefined}
             */
            this["glossary_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * translation progress (checkpointed count)
             * @member
             * @type {number | undefined}
             */
            this["done_tus"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["total_tus"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * pages fully translated (for the resume list)
             * @member
             * @type {number | undefined}
             */
            this["done_pages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * document page count
             * @member
             * @type {number | undefined}
             */
            this["total_pages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 0-based fully-translated pages (to restore batches)
             * @member
             * @type {number[] | undefined}
             */
            this["done_page_list"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updated_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Job}
     */
    static createFrom($$source = {}) {
        const $$createField17_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("done_page_list" in $$parsedSource) {
            $$parsedSource["done_page_list"] = $$createField17_0($$parsedSource["done_page_list"]);
        }
        return new Job(/** @type {Partial<Job>} */($$parsedSource));
    }
}

/**
 * LocalModelInfo is the snapshot the UI shows for the offline (local) engine.
 */
export class LocalModelInfo {
    /**
     * Creates a new LocalModelInfo instance.
     * @param {Partial<LocalModelInfo>} [$$source = {}] - The source object to create the LocalModelInfo.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * remote | local
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("bin_available" in $$source)) {
            /**
             * llama-server binary bundled?
             * @member
             * @type {boolean}
             */
            this["bin_available"] = false;
        }
        if (!("model_present" in $$source)) {
            /**
             * GGUF downloaded/selected?
             * @member
             * @type {boolean}
             */
            this["model_present"] = false;
        }
        if (!("model_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model_path"] = "";
        }
        if (!("model_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model_name"] = "";
        }
        if (!("model_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model_url"] = "";
        }
        if (!("size_mb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_mb"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalModelInfo(/** @type {Partial<LocalModelInfo>} */($$parsedSource));
    }
}

/**
 * Settings is the persisted app configuration (subset of FR-72 for v1 slice).
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("llm_base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_base_url"] = "";
        }
        if (!("llm_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_model"] = "";
        }
        if (!("llm_api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_api_key"] = "";
        }
        if (!("max_concurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_concurrency"] = 0;
        }
        if (!("style" in $$source)) {
            /**
             * formal | concise
             * @member
             * @type {string}
             */
            this["style"] = "";
        }
        if (!("font_family" in $$source)) {
            /**
             * noto | nanum
             * @member
             * @type {string}
             */
            this["font_family"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * replace | interleaved
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("ui_language" in $$source)) {
            /**
             * ko | en
             * @member
             * @type {string}
             */
            this["ui_language"] = "";
        }
        if (!("source_lang" in $$source)) {
            /**
             * auto | en | ko | ja | zh … (document's language)
             * @member
             * @type {string}
             */
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            /**
             * Korean | English | …          (translation language)
             * @member
             * @type {string}
             */
            this["target_lang"] = "";
        }
        if (!("engine_mode" in $$source)) {
            /**
             * Local inference (offline) — run a bundled llama.cpp server against a local GGUF.
             * remote | local  (default remote)
             * @member
             * @type {string}
             */
            this["engine_mode"] = "";
        }
        if (!("local_model_url" in $$source)) {
            /**
             * download source for the GGUF
             * @member
             * @type {string}
             */
            this["local_model_url"] = "";
        }
        if (!("local_model_name" in $$source)) {
            /**
             * display name
             * @member
             * @type {string}
             */
            this["local_model_name"] = "";
        }
        if (!("local_model_path" in $$source)) {
            /**
             * remembered GGUF path (downloaded or picked)
             * @member
             * @type {string}
             */
            this["local_model_path"] = "";
        }
        if (!("local_model_sha256" in $$source)) {
            /**
             * integrity hash (computed on download; verified if set)
             * @member
             * @type {string}
             */
            this["local_model_sha256"] = "";
        }
        if (!("hf_token" in $$source)) {
            /**
             * optional Hugging Face token for gated models
             * @member
             * @type {string}
             */
            this["hf_token"] = "";
        }
        if (!("update" in $$source)) {
            /**
             * Update — online update checking (see internal/update).
             * @member
             * @type {UpdatePrefs}
             */
            this["update"] = (new UpdatePrefs());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField16_0($$parsedSource["update"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * Term is a single glossary entry (03-detailed-design.md §3, §8.2).
 */
export class Term {
    /**
     * Creates a new Term instance.
     * @param {Partial<Term>} [$$source = {}] - The source object to create the Term.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("src" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["src"] = "";
        }
        if (!("dst" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dst"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("case_sensitive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["case_sensitive"] = false;
        }
        if (!("match_inflections" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["match_inflections"] = false;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Term instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Term}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Term(/** @type {Partial<Term>} */($$parsedSource));
    }
}

/**
 * TermsPage is a paged term listing.
 */
export class TermsPage {
    /**
     * Creates a new TermsPage instance.
     * @param {Partial<TermsPage>} [$$source = {}] - The source object to create the TermsPage.
     */
    constructor($$source = {}) {
        if (!("terms" in $$source)) {
            /**
             * @member
             * @type {(Term | null)[]}
             */
            this["terms"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TermsPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TermsPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terms" in $$parsedSource) {
            $$parsedSource["terms"] = $$createField0_0($$parsedSource["terms"]);
        }
        return new TermsPage(/** @type {Partial<TermsPage>} */($$parsedSource));
    }
}

/**
 * TranslateJobOptions mirrors 04 §1.1 TranslateJobOptions (subset for v1 slice).
 */
export class TranslateJobOptions {
    /**
     * Creates a new TranslateJobOptions instance.
     * @param {Partial<TranslateJobOptions>} [$$source = {}] - The source object to create the TranslateJobOptions.
     */
    constructor($$source = {}) {
        if (!("style" in $$source)) {
            /**
             * formal | concise
             * @member
             * @type {string}
             */
            this["style"] = "";
        }
        if (!("enforce_glossary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enforce_glossary"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * replace | interleaved
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("glossary_ids" in $$source)) {
            /**
             * selected glossaries to apply
             * @member
             * @type {number[]}
             */
            this["glossary_ids"] = [];
        }
        if (!("pages" in $$source)) {
            /**
             * 0-based pages for this batch (general-doc mode); empty = whole doc
             * @member
             * @type {number[]}
             */
            this["pages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateJobOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranslateJobOptions}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("glossary_ids" in $$parsedSource) {
            $$parsedSource["glossary_ids"] = $$createField3_0($$parsedSource["glossary_ids"]);
        }
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField4_0($$parsedSource["pages"]);
        }
        return new TranslateJobOptions(/** @type {Partial<TranslateJobOptions>} */($$parsedSource));
    }
}

/**
 * UpdateInfo is the result of a check.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("checked" in $$source)) {
            /**
             * Checked reports whether we actually asked (an auto-check runs at most once a
             * day, so it is false when skipped).
             * @member
             * @type {boolean}
             */
            this["checked"] = false;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("published" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["published"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("canInstall" in $$source)) {
            /**
             * CanInstall reports whether this OS/CPU has an installer and the app can apply
             * it itself.
             * @member
             * @type {boolean}
             */
            this["canInstall"] = false;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["page"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * UpdatePrefs holds the online-update settings.
 */
export class UpdatePrefs {
    /**
     * Creates a new UpdatePrefs instance.
     * @param {Partial<UpdatePrefs>} [$$source = {}] - The source object to create the UpdatePrefs.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * NoAutoCheck, when true, skips the automatic check on startup (a manual check
             * from Settings still works). Stored as "off" so an older settings.json without
             * the field still starts with auto-check on.
             * @member
             * @type {boolean | undefined}
             */
            this["noAutoCheck"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SkipVersion is the version the user chose to skip; honored only by auto-checks.
             * @member
             * @type {string | undefined}
             */
            this["skipVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastCheck is when we last asked (RFC3339); auto-check runs at most once a day.
             * @member
             * @type {string | undefined}
             */
            this["lastCheck"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdatePrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdatePrefs}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdatePrefs(/** @type {Partial<UpdatePrefs>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Term.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = UpdatePrefs.createFrom;
