// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes settings + LLM health to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../internal/engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppInfo returns the program credits for the UI.
 */
export function AppInfo(): $CancellablePromise<$models.About> {
    return $Call.ByID(4280167647);
}

/**
 * AppVersion returns the running app version (shown in the UI top bar).
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(860682005);
}

/**
 * DownloadLocalModel downloads the GGUF from url (or the saved LocalModelURL) into
 * paperKo/models/, with resumable HTTP Range requests, progress events, and SHA-256
 * integrity. The resolved path is remembered (LocalModelPath) so the "run" button is
 * enabled automatically on the next launch when the file is present.
 * 
 * 	UI → DownloadLocalModel → [Range/Resume/Progress/SHA-256] → models/<file>.gguf
 */
export function DownloadLocalModel(url: string): $CancellablePromise<void> {
    return $Call.ByID(2208951544, url);
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2636570673);
}

/**
 * ListModels fetches the available model ids from an OpenAI-compatible server
 * (GET {url}/models) so the UI can offer them as a dropdown instead of a
 * hand-typed model name.
 */
export function ListModels(url: string, apiKey: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2605271170, url, apiKey);
}

/**
 * LocalModelInfo reports the current offline-engine state to the UI.
 */
export function LocalModelInfo(): $CancellablePromise<$models.LocalModelInfo> {
    return $Call.ByID(3408442612);
}

/**
 * PickLocalModel lets the user choose a GGUF they already have (e.g. from LM
 * Studio), avoiding gated-download hassle. Returns the chosen path.
 */
export function PickLocalModel(): $CancellablePromise<string> {
    return $Call.ByID(3644624009);
}

export function SaveSettings(next: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(4042452656, next);
}

/**
 * SetEngineMode switches between "remote" (vLLM/LM Studio) and "local" (bundled
 * llama.cpp). In local mode it starts the server if the model is present.
 */
export function SetEngineMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3736743993, mode);
}

/**
 * StartLocalEngine boots the bundled llama.cpp server against the local GGUF and
 * re-points the translate engine at it.
 */
export function StartLocalEngine(): $CancellablePromise<void> {
    return $Call.ByID(2596198441);
}

/**
 * StopLocalEngine shuts the local server down (frees memory).
 */
export function StopLocalEngine(): $CancellablePromise<void> {
    return $Call.ByID(943448669);
}

/**
 * TestLLMConnection performs a health check against the given server (FR-36).
 */
export function TestLLMConnection(url: string, model: string, apiKey: string): $CancellablePromise<engine$0.HealthInfo | null> {
    return $Call.ByID(985179619, url, model, apiKey);
}
