// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes settings + LLM health to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../internal/engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppInfo returns the program credits for the UI.
 * @returns {$CancellablePromise<$models.About>}
 */
export function AppInfo() {
    return $Call.ByID(4280167647).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AppVersion returns the running app version (shown in the UI top bar).
 * @returns {$CancellablePromise<string>}
 */
export function AppVersion() {
    return $Call.ByID(860682005);
}

/**
 * DownloadLocalModel downloads the GGUF from url (or the saved LocalModelURL) into
 * paperKo/models/, with resumable HTTP Range requests, progress events, and SHA-256
 * integrity. The resolved path is remembered (LocalModelPath) so the "run" button is
 * enabled automatically on the next launch when the file is present.
 * 
 * 	UI → DownloadLocalModel → [Range/Resume/Progress/SHA-256] → models/<file>.gguf
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function DownloadLocalModel(url) {
    return $Call.ByID(2208951544, url);
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2636570673).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListModels fetches the available model ids from an OpenAI-compatible server
 * (GET {url}/models) so the UI can offer them as a dropdown instead of a
 * hand-typed model name.
 * @param {string} url
 * @param {string} apiKey
 * @returns {$CancellablePromise<string[]>}
 */
export function ListModels(url, apiKey) {
    return $Call.ByID(2605271170, url, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * LocalModelInfo reports the current offline-engine state to the UI.
 * @returns {$CancellablePromise<$models.LocalModelInfo>}
 */
export function LocalModelInfo() {
    return $Call.ByID(3408442612).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PickLocalModel lets the user choose a GGUF they already have (e.g. from LM
 * Studio), avoiding gated-download hassle. Returns the chosen path.
 * @returns {$CancellablePromise<string>}
 */
export function PickLocalModel() {
    return $Call.ByID(3644624009);
}

/**
 * @param {$models.Settings} next
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(next) {
    return $Call.ByID(4042452656, next);
}

/**
 * SetEngineMode switches between "remote" (vLLM/LM Studio) and "local" (bundled
 * llama.cpp). In local mode it starts the server if the model is present.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetEngineMode(mode) {
    return $Call.ByID(3736743993, mode);
}

/**
 * StartLocalEngine boots the bundled llama.cpp server against the local GGUF and
 * re-points the translate engine at it.
 * @returns {$CancellablePromise<void>}
 */
export function StartLocalEngine() {
    return $Call.ByID(2596198441);
}

/**
 * StopLocalEngine shuts the local server down (frees memory).
 * @returns {$CancellablePromise<void>}
 */
export function StopLocalEngine() {
    return $Call.ByID(943448669);
}

/**
 * TestLLMConnection performs a health check against the given server (FR-36).
 * @param {string} url
 * @param {string} model
 * @param {string} apiKey
 * @returns {$CancellablePromise<engine$0.HealthInfo | null>}
 */
export function TestLLMConnection(url, model, apiKey) {
    return $Call.ByID(985179619, url, model, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.About.createFrom;
const $$createType1 = $models.Settings.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.LocalModelInfo.createFrom;
const $$createType4 = engine$0.HealthInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
