// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService finds, downloads and installs a newer release from GitHub
 * (internal/update). It is bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check asks whether a newer release exists. When manual (from Settings) it ignores
 * the interval and the skipped version and returns any error; an auto-check stays
 * silent when offline — showing an error on every launch would be annoying.
 * @param {boolean} manual
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function Check(manual) {
    return $Call.ByID(3673454324, manual).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Install downloads the last checked release and installs it. On success it quits
 * the app — macOS swaps in the new bundle and relaunches, Windows hands off to the
 * installer. When it cannot self-apply (dev run, unwritable folder) it opens the
 * downloaded installer for the user and reports that as an error.
 * @returns {$CancellablePromise<void>}
 */
export function Install() {
    return $Call.ByID(1694325063);
}

/**
 * OpenPage opens the release page in the browser. Only a release-repo URL is allowed.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenPage(url) {
    return $Call.ByID(3583622615, url);
}

/**
 * SetAutoCheck turns the automatic startup check on or off.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoCheck(on) {
    return $Call.ByID(1475277269, on);
}

/**
 * Skip stops auto-checks from offering this version again.
 * @param {string} v
 * @returns {$CancellablePromise<void>}
 */
export function Skip(v) {
    return $Call.ByID(3058515315, v);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
