// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DocMeta is the result of document.open.
 */
export class DocMeta {
    /**
     * Creates a new DocMeta instance.
     * @param {Partial<DocMeta>} [$$source = {}] - The source object to create the DocMeta.
     */
    constructor($$source = {}) {
        if (!("doc_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["doc_id"] = "";
        }
        if (!("page_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_count"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("has_text_layer" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_text_layer"] = false;
        }
        if (!("encrypted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["encrypted"] = false;
        }
        if (!("pages_without_text" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["pages_without_text"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocMeta}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pages_without_text" in $$parsedSource) {
            $$parsedSource["pages_without_text"] = $$createField5_0($$parsedSource["pages_without_text"]);
        }
        return new DocMeta(/** @type {Partial<DocMeta>} */($$parsedSource));
    }
}

/**
 * HealthInfo mirrors the engine/vLLM health check.
 */
export class HealthInfo {
    /**
     * Creates a new HealthInfo instance.
     * @param {Partial<HealthInfo>} [$$source = {}] - The source object to create the HealthInfo.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }
        if (!("model_found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["model_found"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HealthInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthInfo(/** @type {Partial<HealthInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
