// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocMeta is the result of document.open.
 */
export interface DocMeta {
    "doc_id": string;
    "page_count": number;
    "title": string;
    "has_text_layer": boolean;
    "encrypted": boolean;
    "pages_without_text": number[] | null;
}

/**
 * HealthInfo mirrors the engine/vLLM health check.
 */
export interface HealthInfo {
    "ok": boolean;
    "latency_ms": number;
    "model_found": boolean;
    "error"?: string;
}
