#!/usr/bin/env python3
"""Bump the PaperKo version in every place at once (single command).

Updates the app version (SemVer) across the Go app, the Python engine and the
Windows installer metadata, and inserts a CHANGELOG stub. The JSON-RPC
protocol/IR versions are intentionally NOT touched.

Usage (from anywhere):
    python3 scripts/bump-version.py 1.0.1
    python3 scripts/bump-version.py            # just print the current version
"""
from __future__ import annotations

import datetime
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (file, regex with one capture group around the version, human label)
TARGETS = [
    (ROOT / "desktop/paperko/services/version.go",
     r'(const Version = ")[0-9]+\.[0-9]+\.[0-9]+(")', "Go app"),
    (ROOT / "engine-py/translate_engine/__init__.py",
     r'(__version__ = ")[0-9]+\.[0-9]+\.[0-9]+(")', "engine"),
    (ROOT / "engine-py/pyproject.toml",
     r'(?m)(^version = ")[0-9]+\.[0-9]+\.[0-9]+(")', "engine pyproject"),
    (ROOT / "desktop/paperko/build/windows/info.json",
     r'("file_version": ")[0-9]+\.[0-9]+\.[0-9]+(")', "Windows file_version"),
    (ROOT / "desktop/paperko/build/windows/info.json",
     r'("ProductVersion": ")[0-9]+\.[0-9]+\.[0-9]+(")', "Windows ProductVersion"),
    # wails_tools.nsh is NOT regenerated by `wails3 package`, so keep it in sync
    # here (it drives the NSIS installer filename + DisplayVersion).
    (ROOT / "desktop/paperko/build/windows/nsis/wails_tools.nsh",
     r'(!define INFO_PRODUCTVERSION ")[0-9]+\.[0-9]+\.[0-9]+(")', "NSIS wails_tools"),
]

SEMVER = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")


def current_version() -> str:
    path, pattern, _ = TARGETS[0]
    m = re.search(pattern, path.read_text(encoding="utf-8"))
    return m.group(0).split('"')[1] if m else "?"


def bump(version: str) -> None:
    if not SEMVER.match(version):
        sys.exit(f"error: '{version}' is not MAJOR.MINOR.PATCH")

    changed = False
    for path, pattern, label in TARGETS:
        text = path.read_text(encoding="utf-8")
        new, n = re.subn(pattern, lambda m: m.group(1) + version + m.group(2), text)
        if n == 0:
            print(f"  ! {label}: pattern not found in {path.name} (skipped)")
            continue
        if new != text:
            path.write_text(new, encoding="utf-8")
            changed = True
        print(f"  ✓ {label:24} → {version}  ({path.relative_to(ROOT)})")

    _changelog_stub(version)
    print()
    if changed:
        print(f"version set to {version}. Remember to fill in CHANGELOG.md and rebuild.")
    else:
        print(f"already at {version}; nothing to change.")


def _changelog_stub(version: str) -> None:
    cl = ROOT / "CHANGELOG.md"
    if not cl.exists():
        return
    text = cl.read_text(encoding="utf-8")
    if f"## [{version}]" in text:
        return  # entry already present
    today = datetime.date.today().isoformat()
    stub = f"## [{version}] — {today}\n\n- _describe changes here_\n\n"
    # insert just before the first existing "## [" entry, else append
    idx = text.find("\n## [")
    if idx == -1:
        cl.write_text(text.rstrip() + "\n\n" + stub, encoding="utf-8")
    else:
        cl.write_text(text[: idx + 1] + stub + text[idx + 1 :], encoding="utf-8")
    print(f"  ✓ CHANGELOG stub inserted for {version}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"current version: {current_version()}")
        print("usage: python3 scripts/bump-version.py <MAJOR.MINOR.PATCH>")
    else:
        bump(sys.argv[1])
